# Generated by Django 4.0 on 2022-01-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerOverlayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Clock'), (2, 'Timer')], default=1)),
                ('value', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TickerOverlayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='SocialOverlayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'League'), (2, 'Twitch'), (3, 'Twitter'), (4, 'YouTube'), (5, 'Instagram'), (6, 'Facebook'), (7, 'Website'), (8, 'Other')], default=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PollOverlayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_blue', models.IntegerField(default=0)),
                ('value_draw', models.IntegerField(default=0)),
                ('value_orange', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OverlayStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_style', models.CharField(default='default', max_length=255)),
                ('start_next_style', models.CharField(default='default', max_length=255)),
                ('ingame_style', models.CharField(default='default', max_length=255)),
                ('ingame_names', models.BooleanField(default=True)),
                ('opbans_style', models.CharField(default='default', max_length=255)),
                ('maps_style', models.CharField(default='default', max_length=255)),
                ('rounds_style', models.CharField(default='default', max_length=255)),
                ('timer_style', models.CharField(default='default', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OverlayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_state', models.BooleanField(default=True)),
                ('start_next_state', models.BooleanField(default=True)),
                ('ingame_state', models.BooleanField(default=True)),
                ('maps_state', models.BooleanField(default=True)),
                ('opbans_state', models.BooleanField(default=True)),
                ('rounds_state', models.BooleanField(default=True)),
                ('social_state', models.BooleanField(default=False)),
                ('poll_state', models.BooleanField(default=False)),
                ('timer_state', models.BooleanField(default=False)),
                ('ticker_state', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
