# Generated by Django 4.0.3 on 2022-03-29 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0005_alter_match_date'),
        ('overlays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasStartStyle', models.BooleanField(default=False)),
                ('hasIngameStyle', models.BooleanField(default=False)),
                ('hasMapBanStyle', models.BooleanField(default=False)),
                ('hasRoundsStyle', models.BooleanField(default=False)),
                ('hasFooterStyle', models.BooleanField(default=False)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='UserOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useCustomDesign', models.BooleanField(default=False)),
                ('customDesignStyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overlays.customdesignstyle')),
                ('overlayLeague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.league')),
                ('overlayMatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='overlaystyle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='polloverlaydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialoverlaydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickeroverlaydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeroverlaydata',
            name='user',
        ),
        migrations.DeleteModel(
            name='OverlayState',
        ),
        migrations.DeleteModel(
            name='OverlayStyle',
        ),
        migrations.DeleteModel(
            name='PollOverlayData',
        ),
        migrations.DeleteModel(
            name='SocialOverlayData',
        ),
        migrations.DeleteModel(
            name='TickerOverlayData',
        ),
        migrations.DeleteModel(
            name='TimerOverlayData',
        ),
    ]
