# Generated by Django 4.0.3 on 2022-03-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('match', '0005_alter_match_date'),
        ('overlays', '0002_customdesignstyle_useroverlay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdesignstyle',
            options={'verbose_name': 'Custom Design Style'},
        ),
        migrations.AlterModelOptions(
            name='useroverlay',
            options={'verbose_name': 'User Overlay'},
        ),
        migrations.AlterField(
            model_name='customdesignstyle',
            name='hasFooterStyle',
            field=models.BooleanField(default=False, verbose_name='has footer style'),
        ),
        migrations.AlterField(
            model_name='customdesignstyle',
            name='hasIngameStyle',
            field=models.BooleanField(default=False, verbose_name='has ingame style'),
        ),
        migrations.AlterField(
            model_name='customdesignstyle',
            name='hasMapBanStyle',
            field=models.BooleanField(default=False, verbose_name='has rounds style'),
        ),
        migrations.AlterField(
            model_name='customdesignstyle',
            name='hasRoundsStyle',
            field=models.BooleanField(default=False, verbose_name='has rounds style'),
        ),
        migrations.AlterField(
            model_name='customdesignstyle',
            name='hasStartStyle',
            field=models.BooleanField(default=False, verbose_name='has start style'),
        ),
        migrations.AlterField(
            model_name='useroverlay',
            name='customDesignStyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overlays.customdesignstyle', verbose_name='custom design style'),
        ),
        migrations.AlterField(
            model_name='useroverlay',
            name='overlayLeague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.league', verbose_name='overlay league'),
        ),
        migrations.AlterField(
            model_name='useroverlay',
            name='overlayMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.match', verbose_name='overlay match'),
        ),
        migrations.AlterField(
            model_name='useroverlay',
            name='useCustomDesign',
            field=models.BooleanField(default=False, verbose_name='uses custom design'),
        ),
    ]
