# Generated by Django 4.0 on 2022-01-04 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('customDesign', models.BooleanField(default=False, verbose_name='custom design')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues')),
                ('logoSmall', models.ImageField(blank=True, null=True, upload_to='leagues', verbose_name='small logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams')),
                ('logoSmall', models.ImageField(blank=True, null=True, upload_to='teams')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('startDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('endDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True, help_text='If checked, this sponsor will be available for all users')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(blank=True, help_text='If set, the sponsor will always be selected when creating a match in the set league. Can be left blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="You can leave this field blank. The season name will then be set automatically, e.g. 'Season 4'", max_length=255)),
                ('seasonNo', models.IntegerField(default=1, verbose_name='season number')),
                ('playdayCount', models.IntegerField(verbose_name='playday count')),
                ('startDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='start date')),
                ('endDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='end date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='Playday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="You can leave this field blank. The playday name will then be set automatically, e.g. 'Playday 4'", max_length=255)),
                ('playdayNo', models.IntegerField(default=1, verbose_name='playday number')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playdays', to='main.season')),
            ],
        ),
    ]
