# Generated by Django 4.0 on 2021-12-22 11:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_season_created_season_lastmodified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playday',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playday',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='season',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='season',
            name='playdayCount',
            field=models.IntegerField(verbose_name='playday count'),
        ),
        migrations.AlterField(
            model_name='season',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='start date'),
        ),
    ]
