# Generated by Django 4.0 on 2021-12-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_playday_created_playday_lastmodified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(help_text="You can leave this field blank. The season name will then be set automatically, e.g. 'Season 4'", max_length=255),
        ),
        migrations.AlterField(
            model_name='season',
            name='seasonNo',
            field=models.IntegerField(blank=True, default=1, verbose_name='season number'),
        ),
    ]
