# Generated by Django 4.0 on 2021-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_season_name_alter_season_seasonno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playday',
            name='name',
            field=models.CharField(blank=True, help_text="You can leave this field blank. The playday name will then be set automatically, e.g. 'Playday 4'", max_length=255),
        ),
    ]
