# Generated by Django 4.0 on 2021-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_playday_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playday',
            name='playday',
        ),
        migrations.AddField(
            model_name='playday',
            name='playdayNo',
            field=models.IntegerField(default=1, verbose_name='playday number'),
        ),
    ]
