# Generated by Django 3.1.3 on 2021-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlaystate',
            name='start_next_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='overlaystyle',
            name='start_next_style',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='maps_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='rounds_state',
            field=models.BooleanField(default=True),
        ),
    ]
