# Generated by Django 3.0.8 on 2020-07-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_auto_20200706_1626'),
        ('overlays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlaystyle',
            name='next_match_style',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.CreateModel(
            name='OverlayState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_state', models.IntegerField(default=0)),
                ('ingame_state', models.IntegerField(default=0)),
                ('maps_state', models.IntegerField(default=0)),
                ('opbans_state', models.IntegerField(default=0)),
                ('rounds_state', models.IntegerField(default=0)),
                ('social_state', models.IntegerField(default=0)),
                ('poll_state', models.IntegerField(default=0)),
                ('timer_state', models.IntegerField(default=0)),
                ('ticker_state', models.IntegerField(default=0)),
                ('next_match_state', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NextMatchOverlayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
