# Generated by Django 3.1.3 on 2021-03-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_matchgroup'),
        ('overlays', '0002_auto_20210309_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchoverlaydata',
            name='match_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.matchgroup'),
        ),
    ]
