# Generated by Django 3.0.8 on 2020-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0002_auto_20200706_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlaystate',
            name='ingame_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='maps_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='next_match_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='opbans_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='poll_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='rounds_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='social_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='start_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='ticker_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overlaystate',
            name='timer_state',
            field=models.BooleanField(default=False),
        ),
    ]
