# Generated by Django 3.0.8 on 2020-07-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200706_1626'),
        ('overlays', '0003_auto_20200706_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchoverlaydata',
            name='current_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Map'),
        ),
    ]
