# Generated by Django 3.0.8 on 2020-07-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0005_auto_20200710_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickeroverlaydata',
            name='timer',
        ),
    ]
