# Generated by Django 3.0.8 on 2020-07-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0006_remove_tickeroverlaydata_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickeroverlaydata',
            name='timer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overlays.TimerOverlayData'),
        ),
    ]
