# Generated by Django 3.0.8 on 2020-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200703_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombspot',
            name='floor',
            field=models.CharField(default='1F', max_length=7),
        ),
    ]
