# Generated by Django 3.0.8 on 2020-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200704_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_restricted',
            field=models.BooleanField(default=True),
        ),
    ]
