# Generated by Django 3.1.3 on 2021-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
