# Generated by Django 3.0.8 on 2020-07-04 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_league_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
