# Generated by Django 3.1.3 on 2021-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_matchgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchgroup',
            name='matches',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Match'),
        ),
    ]
