# Generated by Django 3.1.3 on 2021-04-01 09:56

from django.db import migrations, models


def update_operators(apps, schema_editor):
    Operator = apps.get_model('dashboard', 'Operator')

    # Re-Format operator names to lower case and set new display names
    operators = Operator.objects.all()
    for op in operators:
        op.display_name = op.name
        op.name = op.name.lower()
        op.save()

    # Update special character operator names
    capitao = Operator.objects.get(name="capitao")
    capitao.display_name = "Capitão"
    capitao.save()

    jager = Operator.objects.get(name="jager")
    jager.display_name = "Jäger"
    jager.save()

    nokk = Operator.objects.get(name="nokk")
    nokk.display_name = "Nøkk"
    nokk.save()

    # Add Flores
    flores = Operator(name="flores", display_name="Flores", side='ATK')
    flores.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_auto_20210320_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='side',
            field=models.CharField(choices=[('ATK', 'Attacker'), ('DEF', 'Defender')], max_length=3),
        ),

        migrations.RunPython(update_operators)
    ]
