# Generated by Django 3.0.8 on 2020-07-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200704_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.League'),
        ),
    ]
