# Generated by Django 3.0.8 on 2020-07-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200704_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='share_mode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_win_team', to='dashboard.Team'),
        ),
    ]
