# Generated by Django 3.0.8 on 2020-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='best_of',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='score_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(default='created', max_length=255),
        ),
    ]
