# Generated by Django 3.0.8 on 2020-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_team_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors'),
        ),
    ]
