# Generated by Django 3.0.8 on 2020-07-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200717_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='created', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.MatchState'),
        ),
    ]
