# Generated by Django 3.0.8 on 2020-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200717_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapban',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
