# Generated by Django 3.0.8 on 2020-07-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_mapban_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='dashboard.Map')),
            ],
        ),
    ]
