# Generated by Django 3.0.8 on 2020-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200725_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorbans',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
