# Generated by Django 3.0.8 on 2020-07-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_operatorbans_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='win_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.WinType'),
        ),
    ]
