# Generated by Django 3.0.8 on 2020-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200727_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
