# Generated by Django 3.0.8 on 2020-07-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_round_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='of_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_of_team', to='dashboard.Team'),
        ),
    ]
