# Generated by Django 3.0.8 on 2020-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200731_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues'),
        ),
        migrations.AddField(
            model_name='league',
            name='light_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='light_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors'),
        ),
    ]
