# Generated by Django 3.0.8 on 2020-07-31 08:53

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20200731_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.league_logo_path),
        ),
    ]
