# Generated by Django 3.0.8 on 2020-07-31 09:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200731_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, storage=dashboard.models.OverwriteStorage(), upload_to=dashboard.models.league_logo_path),
        ),
    ]
