# Generated by Django 3.0.8 on 2020-07-31 09:12

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200731_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, storage=dashboard.models.OverwriteStorage(), upload_to=dashboard.models.team_logo_path),
        ),
    ]
