# Generated by Django 3.0.8 on 2020-07-31 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20200731_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=22, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
