# Generated by Django 3.0.8 on 2020-07-31 10:38

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20200731_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, storage=dashboard.models.OverwriteStorage(), upload_to=dashboard.models.league_logo_path, validators=[dashboard.validators.validate_square_logo]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
