# Generated by Django 3.0.8 on 2020-07-31 12:04

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20200731_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, storage=dashboard.models.OverwriteStorage(), upload_to=dashboard.models.team_logo_path, validators=[dashboard.validators.validate_image, dashboard.validators.validate_square_logo]),
        ),
    ]
