# Generated by Django 3.0.8 on 2020-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20200731_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Sponsor'),
        ),
    ]
