# Generated by Django 3.0.8 on 2020-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_match_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='has_custom_overlay',
            field=models.BooleanField(default=False),
        ),
    ]
