# Generated by Django 3.0.8 on 2020-08-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_league_has_custom_overlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
