# Generated by Django 3.0.8 on 2020-09-01 11:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_team_has_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, storage=dashboard.models.OverwriteStorage(), upload_to=dashboard.models.team_logo_path),
        ),
    ]
