# Generated by Django 3.0.8 on 2020-09-01 11:33

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20200901_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo_small',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.team_logo_path),
        ),
    ]
