# Generated by Django 3.0.8 on 2020-09-01 13:48

import dashboard.models
import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20200901_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.team_logo_path, validators=[dashboard.validators.validate_square_logo]),
        ),
    ]
