# Generated by Django 3.0.8 on 2020-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20200901_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
