# Generated by Django 3.0.8 on 2020-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_profile_registration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
