# Generated by Django 3.0.8 on 2020-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20200917_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapban',
            name='play_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mapban',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Playing'), (3, 'Finished'), (4, 'Unknown')], default=1),
        ),
    ]
