# Generated by Django 3.0.8 on 2020-09-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    def type_char_to_int(apps, schema_editor):
        MapBans = apps.get_model('dashboard', 'MapBan')
        for mb in MapBans.objects.all():
            if mb.type == "ban":
                mb.type = 1
            elif mb.type == "pick":
                mb.type = 2
            elif mb.type == "decider":
                mb.type = 3
            elif mb.type == "default_ban":
                mb.type = 4
            mb.save()

    dependencies = [
        ('dashboard', '0051_auto_20200927_1050'),
    ]

    operations = [
        migrations.RunPython(type_char_to_int),
        migrations.AlterField(
            model_name='mapban',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ban'), (2, 'Pick'), (3, 'Decider'), (4, 'Default Ban')]),
        ),
    ]
