# Generated by Django 3.0.8 on 2020-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    def map_play_order_to_map_ban(apps, schema_editor):
        MapPlayOrders = apps.get_model('dashboard', 'MapPlayOrder')
        MapBan = apps.get_model('dashboard', 'MapBan')
        map_play_orders = MapPlayOrders.objects.all()

        for mpo in map_play_orders:
            mb = MapBan.objects.get(match=mpo.match, map=mpo.map)
            if mb.type == 2 or mb.type == 3:
                mb.play_order = mpo.order
            mb.save()

    dependencies = [
        ('dashboard', '0052_auto_20200927_1054'),
    ]

    operations = [
        migrations.RunPython(map_play_order_to_map_ban),
        migrations.AlterField(
            model_name='mapban',
            name='play_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MapPlayOrder',
        ),
    ]
