# Generated by Django 3.0.8 on 2020-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20200927_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapban',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapban',
            name='play_order',
            field=models.IntegerField(default=0),
        ),
    ]
