version: '3'

services:
  backend:
    image: ghcr.io/sthorsten/python-poetry-devcontainer:3.10
    volumes:
      - ../:/repo
    tty: true
    ports:
      - 8000

  frontend:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:16
    volumes:
      - ../:/repo
    tty: true
    ports:
      - 3000

  nginx:
    build:
      context: ''
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../backend/static:/nginx/static
      - ../backend/media:/nginx/media

  redis:
    image: redis:alpine

  postgres:
    image: postgres:14.3-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: caster_dashboard
      POSTGRES_DB: caster_dashboard
      POSTGRES_PASSWORD: caster_dashboard

volumes:
  postgres_data:
