# Generated by Django 4.0 on 2022-01-05 13:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapban',
            name='isDecider',
            field=models.BooleanField(default=False, help_text='Map is Decider Map or Default Ban?', verbose_name='is decider'),
        ),
        migrations.AlterField(
            model_name='match',
            name='additionalUsers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='additional users'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bestOf',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='best of'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 18, 0)),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoreBlue',
            field=models.IntegerField(default=0, verbose_name='score blue'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoreOrange',
            field=models.IntegerField(default=0, verbose_name='score orange'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shareMode',
            field=models.CharField(choices=[('NONE', 'None'), ('READ_ONLY', 'Read Only'), ('READ_WRITE', 'Read and Write')], default='NONE', max_length=255, verbose_name='share mode'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teamBlue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_blue', to='main.team', verbose_name='team blue'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teamOrange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_orange', to='main.team', verbose_name='team orange'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_win_team', to='main.team', verbose_name='win team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winType',
            field=models.CharField(choices=[('NONE', 'None'), ('BLUE_WIN', 'Blue Win'), ('ORANGE_WIN', 'Orange Win'), ('DRAW', 'Draw')], default='NONE', max_length=255, verbose_name='win type'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='atkTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchMapATKTeam', to='main.team', verbose_name='ATK team'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='defTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchMapDEFTeam', to='main.team', verbose_name='DEF team'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='otAtkTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchMapOTATKTeam', to='main.team', verbose_name='OT ATK team'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='otDefTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchMapOTDEFTeam', to='main.team', verbose_name='OT DEF team'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='scoreBlue',
            field=models.IntegerField(default=0, verbose_name='score blue'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='scoreOrange',
            field=models.IntegerField(default=0, verbose_name='score orange'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='winTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchMapWinTeam', to='main.team', verbose_name='win team'),
        ),
        migrations.AlterField(
            model_name='matchmap',
            name='winType',
            field=models.CharField(choices=[('NONE', 'None'), ('BLUE_WIN', 'Blue Win'), ('ORANGE_WIN', 'Orange Win'), ('BLUE_OT_WIN', 'Blue Overtime Win'), ('ORANGE_OT_WIN', 'Orange Overtime Win'), ('DRAW', 'Draw')], default='NONE', max_length=255, verbose_name='win type'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winType',
            field=models.CharField(choices=[('KILLS', 'Kills'), ('DEFUSER_PLANTED', 'Defuser Planted'), ('DEFUSER_DISABLED', 'Defuser Disabled'), ('TIME', 'Time')], default='KILLS', max_length=255),
        ),
    ]
