# Generated by Django 4.0.3 on 2022-03-20 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_map_image'),
        ('main', '0001_initial'),
        ('match', '0002_alter_mapban_isdecider_alter_match_additionalusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 18, 0)),
        ),
        migrations.AlterField(
            model_name='operatorban',
            name='matchMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matchmap', verbose_name='match map'),
        ),
        migrations.AlterField(
            model_name='round',
            name='bombSpot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bombspot', verbose_name='bomb spot'),
        ),
        migrations.AlterField(
            model_name='round',
            name='matchMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matchmap', verbose_name='match map'),
        ),
        migrations.AlterField(
            model_name='round',
            name='openingFragTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_of_team', to='main.team', verbose_name='opening frag team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='roundNo',
            field=models.IntegerField(default=1, verbose_name='round no'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_win_team', to='main.team', verbose_name='win team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winType',
            field=models.CharField(choices=[('KILLS', 'Kills'), ('DEFUSER_PLANTED', 'Defuser Planted'), ('DEFUSER_DISABLED', 'Defuser Disabled'), ('TIME', 'Time')], default='KILLS', max_length=255, verbose_name='win type'),
        ),
    ]
