# Generated by Django 4.0.3 on 2022-03-21 13:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_date_alter_operatorban_matchmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapban',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 18, 0)),
        ),
    ]
