# Generated by Django 4.0 on 2021-12-22 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationToken', models.UUIDField(default=uuid.uuid4)),
                ('accountConfirmed', models.BooleanField(default=False)),
                ('emailConfirmed', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='LeagueAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionGroup', models.CharField(choices=[('BASIC', 'Basic'), ('REGULAR', 'Regular'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagueAccessGroups', to='auth.user')),
            ],
            options={
                'verbose_name': 'League Group',
            },
        ),
    ]
