# Generated by Django 4.0 on 2022-01-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Map',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARN', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=255)),
                ('show', models.BooleanField(default=True)),
                ('showUntil', models.DateTimeField(blank=True, null=True, verbose_name='show until')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('ATK', 'Attacker'), ('DEF', 'Defender')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MapPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maps', models.ManyToManyField(to='core.Map')),
            ],
            options={
                'verbose_name': 'Map Pool',
            },
        ),
        migrations.CreateModel(
            name='BombSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('B', 'Basement'), ('B/1F', 'Basement / First Floor'), ('1F', 'First Floor'), ('1F/2F', 'First / Second Floor'), ('2F', 'Second Floor'), ('2F/3F', 'Second / Third Floor'), ('3F', 'Third Floor')], default='1F', max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
            ],
            options={
                'verbose_name': 'Bomb Spot',
            },
        ),
    ]
