# Generated by Django 4.0.3 on 2022-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps'),
        ),
    ]
