# Generated by Django 4.0 on 2021-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bombspot',
            options={'verbose_name': 'Bomb Spot'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map'},
        ),
        migrations.AlterModelOptions(
            name='mappool',
            options={'verbose_name': 'Map Pool'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARN', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
