# Generated by Django 4.0 on 2021-12-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_valid_until_notification_showuntil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='showUntil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='show until'),
        ),
    ]
